# Generated by Django 4.0.1 on 2022-03-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KidName', models.CharField(max_length=128)),
                ('KigAge', models.CharField(max_length=128)),
                ('ParentPhoneNumber', models.CharField(max_length=128)),
                ('ParentEmailAddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media')),
                ('CreatedOn', models.DateField()),
                ('UpdatedOn', models.DateField()),
                ('IsApproved', models.CharField(max_length=128)),
                ('ApprovedBy', models.CharField(max_length=128)),
                ('FoodGroup', models.CharField(choices=[('1', 'Veg'), ('2', 'Fruit'), ('3', 'Grain'), ('4', 'Protein'), ('5', 'Dairy'), ('6', 'Confectionery'), ('7', 'Unknown')], default='1', max_length=20)),
                ('KidName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kiddata')),
            ],
        ),
    ]
