# Generated by Django 4.0.1 on 2022-03-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_alter_imagetable_updatedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetable',
            name='UpdatedOn',
            field=models.DateField(),
        ),
    ]
